name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Lunarg repo
      run: echo "deb https://packages.lunarg.com/vulkan focal main" | sudo tee /etc/apt/sources.list.d/lunarg-vulkan-focal.list
    - name: Lunarg key
      run: wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
    - name: apt-get update
      run: sudo apt-get update
    - name: Install glfw
      run: sudo apt-get install libglfw3-dev
    - name: Install cmocka
      run: sudo apt-get install libcmocka-dev
    - name: Install shaderc
      run: sudo apt-get install shaderc
    - name: Install vulkan
      run: sudo apt-get install libvulkan-dev vulkan-headers
    - name: Install freetype2
      run: sudo apt-get install libfreetype6-dev
    - name: make
      run: make
    - name: make test
      run: make test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.28
      if: always()
      with:
         files: test-results/**/*.xml
