name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install glfw
      run: sudo apt-get install libglfw3-dev
    - name: Install cmocka
      run: sudo apt-get install libcmocka-dev
    - name: Install shaderc
      run: sudo apt-get install shaderc
    - name: Install vulkan
      run: sudo apt-get install libvulkan-dev
    - name: make
      run: make
    - name: make test
      run: make test
