#version 460

layout(local_size_x = 32, local_size_y = 32) in;

#include "particles3_comp_base.h"

layout(std430, binding=1) buffer DensityBuffer {
    float Rho[];
};

void main()
{
    uint i = gl_GlobalInvocationID.x;
    uint k = gl_GlobalInvocationID.y;

    for (int l = 1; l < nlists; l++) {
        uint roff = l*nn*nn*nn;
        for (int j = 0; j < nn; j++) {
            Rho[off(i,k,j)] += Rho[roff + off(i,k,j)];
        }
    }
}
